name: DevSecOps Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
          cd app
          npm install

    - name: Run app test
      run: | 
          cd app
          node index.js & sleep 5
    
    - name: Build Docker image
      run: |
          cd app 
          docker build -t secure-api .